In [1]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""
import numpy as np
import pandas as pd

df=pd.read_csv('data.csv')

In [2]:
data = df.to_numpy()
training_ind = np.random.rand(len(data)) <= 0.8
training = data[training_ind]
testing = data[~training_ind]
X_train = training[0:32734, 0:48]
Y_train = training[0:32734, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:8222, 0:48]
Y_test = testing[0:8222, 48:49]
Y_test = Y_test.flatten()

#k = 5
#print(KNN(X_train, X_test, Y_train, k))

In [ ]:
def Accuracy(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    
    """

In [ ]:
def Recall(y_true,y_pred):
     """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """

In [ ]:
def Precision(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """

In [ ]:
def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """

In [ ]:
def ConfusionMatrix(y_true,y_pred):
    
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """  

In [4]:
X_train = training[0:800, 0:20]
Y_train = training[0:800, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:200, 0:20]
Y_test = testing[0:200, 48:49]
Y_test = Y_test.flatten()
k = 10

y_pred = np.array([])
for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)
        

from sklearn.metrics import accuracy_score
y_true = Y_test
accuracy_score(y_true, y_pred)

0.84

In [73]:
mat = np.array([[[1,4],[7,5],[3,2]],[[3,5],[5,3],[1,2]],[[7,9],[5,3],[6,2]]])
display(mat)
m = mat.view(dtype=[('', mat.dtype)]*mat.shape[-1])
m.sort(axis=1)
mat
display(mat[:,0:2,:])

array([[[1, 4],
        [7, 5],
        [3, 2]],

       [[3, 5],
        [5, 3],
        [1, 2]],

       [[7, 9],
        [5, 3],
        [6, 2]]])

array([[[1, 4],
        [3, 2]],

       [[1, 2],
        [3, 5]],

       [[5, 3],
        [6, 2]]])

In [62]:
A = np.array([[1,2,3],[3,1,6]])
display(A)
B = np.array([[2,7,2],[8,2,4]])
display(B)
C = np.true_divide(A,B)
display(C)
mini = np.min(A,axis = 0)
maxi = np.max(A,axis = 0)
#display(mini)
min2 = np.tile(mini, (A.shape[0],1))
#display(min2)


array([[1, 2, 3],
       [3, 1, 6]])

array([[2, 7, 2],
       [8, 2, 4]])

array([[0.5       , 0.28571429, 1.5       ],
       [0.375     , 0.5       , 1.5       ]])

In [85]:
X_train = training[0:32734, 0:48]
Y_train = training[0:32734, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:8222, 0:48]
Y_test = testing[0:8222, 48:49]
Y_test = Y_test.flatten()

#display(X_train)
X_min = np.min(X_train,axis = 0)
#display(X_min)
X_max = np.max(X_train,axis = 0)
X_minMat = np.tile(X_min, (X_train.shape[0],1))
X_maxMat = np.tile(X_max, (X_train.shape[0],1))
X_train_normal = np.true_divide(X_train-X_minMat, X_maxMat-X_minMat)
#display(X_maxMat)

X_min2 = np.min(X_test,axis = 0)
#display(X_min)
X_max2 = np.max(X_test,axis = 0)
X_minMat2 = np.tile(X_min2, (X_test.shape[0],1))
X_maxMat2 = np.tile(X_max2, (X_test.shape[0],1))
X_test_normal = np.true_divide(X_test-X_minMat2, X_maxMat2-X_minMat2)



#display(final)
X_train_normal = np.transpose(X_train_normal)
dist = np.dot(X_test_normal, X_train_normal)


k = 6
trueLabel = np.tile(Y_train, (X_test_normal.shape[0],1))
Dist = np.array(np.dstack((dist, trueLabel)))
#Dist = np.array(Dist[0:3,0:3,0:2])
#display(Dist)
D = Dist.view(dtype=[('', Dist.dtype)]*Dist.shape[-1])
D.sort(axis=1)
#display(Dist)
topK = sortDist[:,0:k,:]
#display(topK)
topK = topK[:,:,1].astype(int)
display(topK)
Y_pred = np.array([])
for vector in topK:
    counts = np.bincount(vector)
    majority = np.argmax(counts)
    Y_pred = np.append(Y_pred,majority)
display(Y_pred)
#=sortDist = np.sort(sortDist, axis = 2)
#display(sortDist)
#sortDist = sorted(data, key=lambda x: x[1])


MemoryError: 

In [20]:
def KNN(X_train,X_test,Y_train, k):
    y_pred = np.array([])
    for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)
    return y_pred
        
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    ##NP.tile np.repeat
    ##np.lin(norx)
    ##creating a matrix with same test row repeating operation on entire train matrix
    ##(A-B)^2 = A^2 - 2AB + B^2
    ##cosine distance also an option
    :rtype: numpy.ndarray
    """

In [54]:
d = np.array([])
d = np.append(d, 2)
np.append(d, 3)

array([2., 3.])

In [42]:
X_train.shape

(32717, 48)

In [43]:
X_test.shape

(8222, 48)

In [40]:
X_train **2

array([[2.05453693e-11, 7.40220849e-10, 1.33333209e-08, ...,
        2.26442304e+00, 2.26442304e+00, 2.26472401e+00],
       [3.36135556e-12, 4.44848981e-11, 1.18875409e-10, ...,
        2.24340484e+00, 2.24340484e+00, 2.24340484e+00],
       [9.96159844e-12, 5.88381044e-11, 1.97262025e-08, ...,
        2.24340484e+00, 2.24340484e+00, 2.24370441e+00],
       ...,
       [3.03777346e-11, 5.93019904e-10, 1.76694123e-07, ...,
        2.24670121e+00, 2.24670121e+00, 2.24670121e+00],
       [1.55504036e-11, 7.38912160e-13, 2.53096281e-10, ...,
        2.24640144e+00, 2.24610169e+00, 2.24640144e+00],
       [3.88689903e-11, 4.35877244e-09, 1.11767184e-08, ...,
        2.23622116e+00, 2.23652025e+00, 2.23622116e+00]])

In [ ]:
def RandomForest(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: numpy.ndarray
    """

In [ ]:
def PCA(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: numpy.ndarray
    """  

In [ ]:
def Kmeans(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """

In [ ]:
def SklearnSupervisedLearning(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """
"

In [ ]:
def SklearnVotingClassifier(X_train,Y_train,X_test):
    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """


"""
Create your own custom functions for Matplotlib visualization of hyperparameter search. 
Make sure that plots are labeled and proper legends are used
""