In [90]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""
import numpy as np
import pandas as pd

df=pd.read_csv('data.csv')

In [91]:
data = df.to_numpy()
training_ind = np.random.rand(len(data)) <= 0.8
training = data[training_ind]
testing = data[~training_ind]
X_train = training[0:32734, 0:48]
Y_train = training[0:32734, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:8222, 0:48]
Y_test = testing[0:8222, 48:49]
Y_test = Y_test.flatten()

#k = 5
#print(KNN(X_train, X_test, Y_train, k))

In [4]:
y_true = np.array([0,1,1,2])
y_pred = np.array([0,1,1,1])
A = ConfusionMatrix(y_true,y_pred)
B = np.array([])
#display(A[0,:])
#display(np.sum(A[0,:]))
display(y_true.shape[0])
display(y_true.shape[0]-1)
acct = A[0,0]/(np.sum(A[0,:])
#for i in range(y_true.shape[0]-1):
#    acct = A[i,i]/(np.sum(A[i,:]))
#    display(acct)
#    B = np.append(B,acct)
#display(B)

SyntaxError: unexpected EOF while parsing (<ipython-input-4-ac7e19be4af7>, line 14)

In [ ]:
y_true = np.array([0,1,1,2])
y_pred = np.array([0,1,1,1])
A = ConfusionMatrix(y_true,y_pred)
B = np.array([])
display(A.shape)
for i in range(A.shape[0]):
    display(i)
    sumRow = (np.sum(A[i,:]))
    if sumRow == 0:
        sumRow = 1
    acct = A[i,i]/sumRow
    B = np.append(B,acct)
mean = np.mean(B)
display(B, mean)


In [ ]:
display(Recall(y_true,y_pred))
display(Precision(y_true,y_pred))
display(Accuracy(y_true,y_pred))

In [ ]:
def Accuracy(y_true,y_pred):
    A = ConfusionMatrix(y_true,y_pred)
    trueVal = np.sum(A.diagonal())
    total = np.sum(A)
    return trueVal/total
    
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    
    """

In [ ]:
def Recall(y_true,y_pred):
    A = ConfusionMatrix(y_true,y_pred)
    B = np.array([])
    for i in range(A.shape[0]):
        sumCol = (np.sum(A[:,i]))
        if sumCol == 0:
            sumCol = 1
        acct = A[i,i]/sumCol
        B = np.append(B,acct)
    mean = np.mean(B)
    return mean

In [ ]:
def Precision(y_true,y_pred):
    A = ConfusionMatrix(y_true,y_pred)
    B = np.array([])
    for i in range(A.shape[0]):
        sumRow = (np.sum(A[i,:]))
        if sumRow == 0:
            sumRow = 1
        acct = A[i,i]/sumRow
        B = np.append(B,acct)
    mean = np.mean(B)
    return mean
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """

In [ ]:
def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """

In [ ]:
def ConfusionMatrix(y_true,y_pred):
    numClass = np.unique(y_true).shape[0]
    C = y_true*numClass + y_pred
    C = np.bincount(C)
    C = np.pad(C, (0, numClass**2-C.shape[0]), 'constant')
    D = C.reshape(numClass,numClass)
    return np.transpose(D)
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """  

In [ ]:
y_true = np.array([0,1,1,2])
y_pred = np.array([0,1,1,1])
#display(y_true)
#display(np.unique(y_true))
numClass = np.unique(y_true).shape[0]
#display(numClass)
C = y_true*numClass + y_pred
C = np.bincount(C)
C = np.pad(C, (0, numClass**2-C.shape[0]), 'constant')
#display(C)
D = C.reshape(numClass,numClass)
#display(D)

In [ ]:
X_train = training[0:800, 0:20]
Y_train = training[0:800, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:200, 0:20]
Y_test = testing[0:200, 48:49]
Y_test = Y_test.flatten()
k = 10

y_pred = np.array([])
for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)
        

from sklearn.metrics import accuracy_score
y_true = Y_test
accuracy_score(y_true, y_pred)

In [ ]:
mat = np.array([[[1,4,5,6],[7,2,5,5],[3,1,4,2]],[[3,5,6,5],[5,2,7,3],[8,6,1,2]]])
display(mat)
#mat_sort = mat[mat[:,2].argsort()[::-1]]
#mat = mat[np.arange(len(mat))[:,np.newaxis]]
#m = mat.view(dtype=[('', mat.dtype)]*mat.shape[-1])
#m.sort(axis=1)
#mat
I, J, K = np.ogrid[tuple(map(slice, mat.shape))]
# I, J, K are the identity indices in the sense that (A == A[I, J, K]).all()
newK = np.argsort(mat[0],axis=-1) # first axis of A[1] is second axis of A
display(mat[I, J, newK])
#display(mat)

In [ ]:
A = np.array([[1,4,5,6,7],[7,2,5,5,3],[3,1,4,2,7],[6,2,4,2,7]])
#A = np.transpose(A)
B = np.array([[3,5,6,5,2],[5,2,7,3,1],[8,6,1,2,2],[5,2,2,2,5]])
#B = np.transpose(B)
C = np.array([A, B])
I, J, K = np.ogrid[tuple(map(slice, C.shape))]
# I, J, K are the identity indices in the sense that (A == A[I, J, K]).all()
newK = np.argsort(C[0],axis=-1) # first axis of A[1] is second axis of A
display(C[I, J, newK])

In [ ]:
A = np.array([[1,2,3],[3,1,6]])
display(A)
B = np.array([[2,7,2],[8,2,4]])
display(B)
C = np.true_divide(A,B)
display(C)
mini = np.min(A,axis = 0)
maxi = np.max(A,axis = 0)
#display(mini)
min2 = np.tile(mini, (A.shape[0],1))
#display(min2)


In [16]:
A = np.array([[1,2,1],[4,5,1],[2,3,1]])
display(A)
B = np.array([[1,2,1],[2,1,2]])
display(B)
B_new = B[:,np.newaxis]
display(B_new)
C = A+B_new
display(C)
display(B_new.shape)
C = np.sum(C,axis=2)
display(C)

array([[1, 2, 1],
       [4, 5, 1],
       [2, 3, 1]])

array([[1, 2, 1],
       [2, 1, 2]])

array([[[1, 2, 1]],

       [[2, 1, 2]]])

array([[[2, 4, 2],
        [5, 7, 2],
        [3, 5, 2]],

       [[3, 3, 3],
        [6, 6, 3],
        [4, 4, 3]]])

(2, 1, 3)

array([[ 8, 14, 10],
       [ 9, 15, 11]])

In [ ]:
#display(X_train.shape, X_test.shape)
X_min = np.min(X_train,axis = 0)
X_max = np.max(X_train,axis = 0)
X_minMat = np.tile(X_min, (X_train.shape[0],1))
X_maxMat = np.tile(X_max, (X_train.shape[0],1))
X_train_normal = np.true_divide(X_train-X_minMat, X_maxMat-X_minMat)


X_min2 = np.min(X_test,axis = 0)
X_max2 = np.max(X_test,axis = 0)
X_minMat2 = np.tile(X_min2, (X_test.shape[0],1))
X_maxMat2 = np.tile(X_max2, (X_test.shape[0],1))
X_test_normal = np.true_divide(X_test-X_minMat2, X_maxMat2-X_minMat2)


In [3]:
#EUCLIDEAN
X_train = training[0:800, 0:20]
Y_train = training[0:800, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:200, 0:20]
Y_test = testing[0:200, 48:49]
Y_test = Y_test.flatten()
X_train_normal = X_train
X_test_normal = X_test

A2 = np.square(X_train_normal)
B2 = np.square(X_test_normal)
B2_new = B2[:,np.newaxis]
A2andB2 = A2+B2_new
A2andB2 = np.sum(A2andB2,axis=2)
X_train_normalnew = np.transpose(X_train_normal)
AB2 = np.multiply(2, np.dot(X_test_normal,X_train_normalnew))
Euclidean = np.sqrt(A2andB2 + AB2)
display(Euclidean, Euclidean.shape)

k = 6
trueLabel = np.tile(Y_train, (X_test_normal.shape[0],1))
Dist = np.array([Euclidean, trueLabel])

I, J, K = np.ogrid[tuple(map(slice, Dist.shape))]
# I, J, K are the identity indices in the sense that (A == A[I, J, K]).all()
newK = np.argsort(Dist[0],axis=-1) # first axis of A[1] is second axis of A
Dist = Dist[I, J, newK]
#a,b = (X_test.shape[0],X_train.shape[0])
display(Dist)
topK = Dist[1,:,0:k]
display(topK)
#display(topK)
topK = topK.astype(int)
display(topK)
#display(topK)
Y_pred = np.array([])
for vector in topK:
    counts = np.bincount(vector)
    majority = np.argmax(counts)
    Y_pred = np.append(Y_pred,majority)
display(Y_pred.shape)
from sklearn.metrics import accuracy_score
y_true = Y_test
display(accuracy_score(y_true, Y_pred))

array([[4.56154869, 4.62418325, 4.30597545, ..., 4.59311981, 4.52319435,
        4.40996669],
       [4.58427501, 4.64865525, 4.32998554, ..., 4.61786109, 4.54721027,
        4.42933797],
       [4.46773207, 4.53164515, 4.21312257, ..., 4.50045221, 4.43044681,
        4.31401073],
       ...,
       [5.11803095, 5.18198247, 4.86339949, ..., 5.15119867, 5.08058677,
        4.9634763 ],
       [3.176862  , 3.24036528, 2.92186272, ..., 3.20974969, 3.13915709,
        3.0250442 ],
       [4.15079006, 4.21377148, 3.89544712, ..., 4.18283608, 4.1126884 ,
        3.99886568]])

(200, 800)

array([[[ 3.78733215,  3.86520559,  3.86680905, ...,  5.99440856,
          5.9983311 ,  6.0059101 ],
        [ 3.81192134,  3.88705305,  3.88706154, ...,  6.01582054,
          6.01976314,  6.02736625],
        [ 3.6944891 ,  3.77077795,  3.77234789, ...,  5.89977181,
          5.90370438,  5.91128966],
        ...,
        [ 4.34523964,  4.42092601,  4.42122706, ...,  6.54983161,
          6.55377285,  6.56137866],
        [ 2.40386772,  2.48023586,  2.48183471, ...,  4.60944312,
          4.6133699 ,  4.62095523],
        [ 3.37697442,  3.45429189,  3.45589164, ...,  5.58350024,
          5.58742548,  5.5950075 ]],

       [[10.        ,  3.        ,  3.        , ...,  4.        ,
          4.        ,  4.        ],
        [10.        ,  7.        ,  3.        , ...,  4.        ,
          4.        ,  4.        ],
        [10.        ,  3.        ,  3.        , ...,  4.        ,
          4.        ,  4.        ],
        ...,
        [10.        ,  3.        ,  7.        , ...,  

array([[10.,  3.,  3.,  7.,  7.,  7.],
       [10.,  7.,  3.,  3.,  7.,  7.],
       [10.,  3.,  3.,  7.,  7.,  7.],
       ...,
       [10.,  3.,  7.,  3.,  7.,  7.],
       [10.,  3.,  3.,  7.,  7.,  7.],
       [10.,  3.,  3.,  7.,  7.,  7.]])

array([[10,  3,  3,  7,  7,  7],
       [10,  7,  3,  3,  7,  7],
       [10,  3,  3,  7,  7,  7],
       ...,
       [10,  3,  7,  3,  7,  7],
       [10,  3,  3,  7,  7,  7],
       [10,  3,  3,  7,  7,  7]])

(200,)

0.065

In [6]:
#COSINE GARBAGE ABSOLUTE TRAHS
X_train = training[0:8000, 0:48]
Y_train = training[0:8000, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:2000, 0:48]
Y_test = testing[0:2000, 48:49]
Y_test = Y_test.flatten()

#display(X_train.shape, X_test.shape)
X_min = np.min(X_train,axis = 0)
X_max = np.max(X_train,axis = 0)
X_minMat = np.tile(X_min, (X_train.shape[0],1))
X_maxMat = np.tile(X_max, (X_train.shape[0],1))
X_train_normal = np.true_divide(X_train-X_minMat, X_maxMat-X_minMat)

X_min2 = np.min(X_test,axis = 0)
X_max2 = np.max(X_test,axis = 0)
X_minMat2 = np.tile(X_min2, (X_test.shape[0],1))
X_maxMat2 = np.tile(X_max2, (X_test.shape[0],1))
X_test_normal = np.true_divide(X_test-X_minMat2, X_maxMat2-X_minMat2)
#display(X_train_normal.shape, X_test_normal.shape)

X_train_L1norm = np.apply_along_axis(np.linalg.norm, 1, X_train_normal)
X_test_L1norm = np.apply_along_axis(np.linalg.norm, 1, X_test_normal)
#display(X_train_L1norm.shape, X_test_L1norm.shape)

C = np.transpose(np.tile(X_train_L1norm, (X_train.shape[1],1)))
D = np.transpose(np.tile(X_test_L1norm, (X_test.shape[1],1)))
#display(C.shape,D.shape)

X_train_final = np.true_divide(X_train_normal,C)
X_test_final = np.true_divide(X_test_normal,D)

X_train_final = np.transpose(X_train_final)
#display(X_test_final.shape, X_train_final.shape)

dist = np.dot(X_test_final, X_train_final)
k = 6
trueLabel = np.tile(Y_train, (X_test_final.shape[0],1))
ones = np.ones((X_test.shape[0],X_train.shape[0]))
Dist = np.subtract(ones,dist)
Dist = np.array([Dist, trueLabel])

I, J, K = np.ogrid[tuple(map(slice, Dist.shape))]
# I, J, K are the identity indices in the sense that (A == A[I, J, K]).all()
newK = np.argsort(Dist[0],axis=-1) # first axis of A[1] is second axis of A
Dist = Dist[I, J, newK]
#a,b = (X_test.shape[0],X_train.shape[0])
display(Dist)
topK = Dist[1,:,0:k]
display(topK)
#display(topK)
topK = topK.astype(int)
display(topK)
#display(topK)
Y_pred = np.array([])
for vector in topK:
    counts = np.bincount(vector)
    majority = np.argmax(counts)
    Y_pred = np.append(Y_pred,majority)
display(Y_pred.shape)
from sklearn.metrics import accuracy_score
y_true = Y_test
display(accuracy_score(y_true, Y_pred))

array([[[1.06712859e-02, 1.08226540e-02, 1.10574405e-02, ...,
         2.92841730e-01, 2.94245422e-01, 2.97682827e-01],
        [7.90492197e-03, 8.26470993e-03, 8.48467208e-03, ...,
         4.18210192e-01, 4.18645364e-01, 4.21285074e-01],
        [1.17698566e-02, 1.25708989e-02, 1.27096657e-02, ...,
         3.01783358e-01, 3.02470321e-01, 3.03002709e-01],
        ...,
        [1.24217951e-02, 1.28415148e-02, 1.28456472e-02, ...,
         2.77452034e-01, 2.79875776e-01, 2.87272537e-01],
        [1.14967993e-02, 1.28375296e-02, 1.28740186e-02, ...,
         2.35169962e-01, 2.45143444e-01, 2.65554642e-01],
        [1.65136654e-02, 1.71756100e-02, 1.76578767e-02, ...,
         2.67775242e-01, 2.70404970e-01, 2.78732080e-01]],

       [[6.00000000e+00, 9.00000000e+00, 9.00000000e+00, ...,
         1.10000000e+01, 1.10000000e+01, 1.10000000e+01],
        [3.00000000e+00, 3.00000000e+00, 3.00000000e+00, ...,
         1.10000000e+01, 1.10000000e+01, 1.10000000e+01],
        [3.00000000e+00, 

array([[6., 9., 9., 6., 6., 6.],
       [3., 3., 3., 4., 5., 3.],
       [3., 8., 3., 9., 3., 8.],
       ...,
       [9., 9., 9., 9., 9., 9.],
       [2., 2., 2., 2., 2., 2.],
       [8., 8., 8., 8., 1., 6.]])

array([[6, 9, 9, 6, 6, 6],
       [3, 3, 3, 4, 5, 3],
       [3, 8, 3, 9, 3, 8],
       ...,
       [9, 9, 9, 9, 9, 9],
       [2, 2, 2, 2, 2, 2],
       [8, 8, 8, 8, 1, 6]])

(2000,)

0.6895

In [ ]:
topK = Dist[:,0:k,:]
#display(topK)
topK = topK[:,:,1].astype(int)
#display(topK)
Y_pred = np.array([])
for vector in topK:
    counts = np.bincount(vector)
    majority = np.argmax(counts)
    Y_pred = np.append(Y_pred,majority)
#display(Y_pred)
#=sortDist = np.sort(sortDist, axis = 2)
#display(sortDist)
#sortDist = sorted(data, key=lambda x: x[1])
from sklearn.metrics import accuracy_score
y_true = Y_test
display(y_true.shape)
display(Y_pred.shape)
display(accuracy_score(y_true, Y_pred))

In [ ]:
def KNN(X_train,X_test,Y_train, k):
    y_pred = np.array([])
    for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)
    return y_pred
        
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    ##NP.tile np.repeat
    ##np.lin(norx)
    ##creating a matrix with same test row repeating operation on entire train matrix
    ##(A-B)^2 = A^2 - 2AB + B^2
    ##cosine distance also an option
    :rtype: numpy.ndarray
    """

In [ ]:
d = np.array([])
d = np.append(d, 2)
np.append(d, 3)

In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
X_train **2

In [ ]:
def RandomForest(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: numpy.ndarray
    """

In [82]:
#Demo of centering data (mean = 0)

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
display(A)

mean = A.mean(axis=0)
display(mean)
display(mean.shape)

new_A = A - mean
# Or use newaxis:
# new_A = A - mean[np.newaxis, :]

display(new_A)

display(A.mean())
display(new_A.mean())

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([5.5, 6.5, 7.5])

(3,)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

6.5

0.0

In [56]:
#Demo of standardizing data (s.d. = 1)

display(new_A)

new_sd = np.std(new_A, axis=0)
display(new_sd)

newer_A = new_A / new_sd
display(newer_A)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

array([3.35410197, 3.35410197, 3.35410197])

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])

In [68]:
#Covariance matrix demo

Z = np.array([[0, 2], [2, 0]])
display(Z)
cov = np.cov(Z)
display(cov)

array([[0, 2],
       [2, 0]])

array([[ 2., -2.],
       [-2.,  2.]])

In [69]:
#Demo of eigendecomposition

A = np.array([[5, 1],[3, 3]])

e_vals, e_vects = np.linalg.eig(A)

display(e_vals)
display(e_vects)

display(e_vals[0])
display(e_vects[:, 0])
e_recomp = e_vals[0] * e_vects[:, 0]
display(e_recomp)

array([6., 2.])

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

6.0

array([0.70710678, 0.70710678])

array([4.24264069, 4.24264069])

In [76]:
#Sorting eigenvectors based on eigenvalues

eigenValues = np.array([1, 8, 4])
eigenVectors = np.array([[4, 8, 7], [9, 5, 1], [2, 2, 5]])

display(eigenValues)
display(eigenVectors)

idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

display(eigenValues)
display(eigenVectors)

array([1, 8, 4])

array([[4, 8, 7],
       [9, 5, 1],
       [2, 2, 5]])

array([8, 4, 1])

array([[8, 7, 4],
       [5, 1, 9],
       [2, 5, 2]])

In [86]:
#Calculate Z* = ZP*

# Z_star = Z

a = np.array([[1, 0], 
              [0, 1]])

b = np.array([[4, 1], 
              [2, 2]])

display(np.dot(a, b))
display(a @ b)

# array([[4, 1],
#        [2, 2]])

array([[4, 1],
       [2, 2]])

array([[4, 1],
       [2, 2]])

In [89]:
# Determine the top N features to keep

M = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
topN = M[:, :N]
display(topN)

array([[1],
       [4],
       [7]])

In [147]:
#PRACTICE

X_train = training[0:5, 0:5]
display(X_train)
N = 2

#1) Center the data (mean=0) and standardize (standard deviation = 1) (call matrix Z)
#Center data
mean = X_train.mean(axis=0)
# display(mean)
# display(mean.shape)
# centered_X = X_train - mean
# Or use newaxis:
center_X = X_train - mean[np.newaxis, :]
display(center_X)
# display(X_train.mean())
# display(center_X.mean())

#Standardize data
sd = np.std(center_X, axis=0)
# display(sd)
Z = center_X / sd
display(Z)

#2) Find the covariance matrix of Z (Zt*Z)
display(Z)
cov = np.cov(Z)
display(cov)

#3) Using eigendecomposition, decompose (Zt*Z) into PDP^-1
e_vals, e_vects = np.linalg.eig(cov)

display(e_vals)
display(e_vects)

#4) Sort the eigenvectors by their corresponding eigenvalues from largest to smallest (call new matrix P*)
display(e_vals)
display(e_vects)

idx = e_vals.argsort()[::-1]   
e_vals = e_vals[idx]
P_star = e_vects[:,idx]

display(e_vals)
display(P_star)

#5) Calculate Z* = ZP* (new matrix Z* is a centered/standardized version of X's principle components)
Z_star = Z @ P_star
display(Z_star)

#6) Determine the top N features to keep
topN = Z_star[:, :N]
display(topN)

array([[ 1.4055e-05,  4.4589e-05,  9.4860e-05, -5.2550e-06,  1.0533e-04],
       [ 5.4193e-06, -1.0994e-05, -6.0426e-05,  3.2712e-06, -3.3251e-06],
       [-1.2952e-05, -1.6223e-05,  2.7494e-04, -1.2440e-05, -5.8102e-05],
       [-1.0194e-05, -3.0570e-06, -2.6091e-04,  1.3139e-06, -8.2072e-06],
       [-1.4395e-05,  7.2051e-05, -1.3032e-04, -1.2995e-05,  5.1771e-05]])

array([[ 1.766834e-05,  2.731580e-05,  1.112312e-04, -3.402000e-08,
         8.783666e-05],
       [ 9.032640e-06, -2.826720e-05, -4.405480e-05,  8.492180e-06,
        -2.081844e-05],
       [-9.338660e-06, -3.349620e-05,  2.913112e-04, -7.219020e-06,
        -7.559534e-05],
       [-6.580660e-06, -2.033020e-05, -2.445388e-04,  6.534880e-06,
        -2.570054e-05],
       [-1.078166e-05,  5.477780e-05, -1.139488e-04, -7.774020e-06,
         3.427766e-05]])

array([[ 1.56104295,  0.78326296,  0.59978997, -0.00504487,  1.56757145],
       [ 0.79805681, -0.81054375, -0.2375559 ,  1.25931726, -0.37153499],
       [-0.82509446, -0.96048195,  1.57083208, -1.07051858, -1.3491075 ],
       [-0.58141811, -0.58295538, -1.31862212,  0.9690665 , -0.45866308],
       [-0.95258719,  1.57071812, -0.61444404, -1.15282031,  0.61173411]])

array([[ 1.56104295,  0.78326296,  0.59978997, -0.00504487,  1.56757145],
       [ 0.79805681, -0.81054375, -0.2375559 ,  1.25931726, -0.37153499],
       [-0.82509446, -0.96048195,  1.57083208, -1.07051858, -1.3491075 ],
       [-0.58141811, -0.58295538, -1.31862212,  0.9690665 , -0.45866308],
       [-0.95258719,  1.57071812, -0.61444404, -1.15282031,  0.61173411]])

array([[ 0.45137012, -0.17378062, -0.20828692, -0.27526316,  0.20596059],
       [-0.17378062,  0.74822113, -0.19099838,  0.49103103, -0.87447316],
       [-0.20828692, -0.19099838,  1.41223486, -0.62240413, -0.39054542],
       [-0.27526316,  0.49103103, -0.62240413,  0.6969715 , -0.29033524],
       [ 0.20596059, -0.87447316, -0.39054542, -0.29033524,  1.34939323]])

array([2.23082022e+00, 1.87471612e+00, 5.38363278e-01, 1.16360450e-16,
       1.42912254e-02])

array([[-0.19218966,  0.07408832,  0.81470931, -0.4472136 , -0.30630506],
       [ 0.56564357,  0.09970042,  0.13185132, -0.4472136 ,  0.67284649],
       [-0.01099026, -0.86014638, -0.2144233 , -0.4472136 , -0.11853295],
       [ 0.35602963,  0.41091189, -0.41543504, -0.4472136 , -0.57602782],
       [-0.71849328,  0.27544576, -0.31670229, -0.4472136 ,  0.32801935]])

array([2.23082022e+00, 1.87471612e+00, 5.38363278e-01, 1.16360450e-16,
       1.42912254e-02])

array([[-0.19218966,  0.07408832,  0.81470931, -0.4472136 , -0.30630506],
       [ 0.56564357,  0.09970042,  0.13185132, -0.4472136 ,  0.67284649],
       [-0.01099026, -0.86014638, -0.2144233 , -0.4472136 , -0.11853295],
       [ 0.35602963,  0.41091189, -0.41543504, -0.4472136 , -0.57602782],
       [-0.71849328,  0.27544576, -0.31670229, -0.4472136 ,  0.32801935]])

array([2.23082022e+00, 1.87471612e+00, 5.38363278e-01, 1.42912254e-02,
       1.16360450e-16])

array([[-0.19218966,  0.07408832,  0.81470931, -0.30630506, -0.4472136 ],
       [ 0.56564357,  0.09970042,  0.13185132,  0.67284649, -0.4472136 ],
       [-0.01099026, -0.86014638, -0.2144233 , -0.11853295, -0.4472136 ],
       [ 0.35602963,  0.41091189, -0.41543504, -0.57602782, -0.4472136 ],
       [-0.71849328,  0.27544576, -0.31670229,  0.32801935, -0.4472136 ]])

array([[-0.99164618,  0.10754743,  0.75210389,  0.49486525, -2.01542284],
       [ 0.10605332,  0.59777868,  0.18875204, -1.6089346 , -0.28520575],
       [ 0.18620867, -2.3195306 , -0.26367958, -0.40560654,  1.17812626],
       [ 0.47105231,  1.30487501, -0.52513141, -0.76650763,  0.88217005],
       [ 0.22833188,  0.30932949, -0.15204493,  2.28618352,  0.24033228]])

array([[-0.99164618,  0.10754743],
       [ 0.10605332,  0.59777868],
       [ 0.18620867, -2.3195306 ],
       [ 0.47105231,  1.30487501],
       [ 0.22833188,  0.30932949]])

In [213]:
def PCA(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: numpy.ndarray
    """
    
    #1) Center the data (mean=0) and standardize (standard deviation = 1) (call matrix Z)
    #Center the data
    mean = X_train.mean(axis=0)
    center_X = X_train - mean[np.newaxis, :]
#     display(center_X)    
    
    #Standardize the data
    sd = np.std(center_X, axis=0)
    Z = center_X / sd
#     display(Z)
    
    #2) Find the covariance matrix of Z (Zt*Z)
    cov = np.cov(Z)
#     display(cov)
    
    #3) Using eigendecomposition, decompose (Zt*Z) into PDP^-1
    #Where P = matrix of eigenvectors, D = vector of eigenvalues which corresponds to P
    e_vals, e_vects = np.linalg.eig(cov)
#     display(e_vals)
#     display(e_vects)
    
    #4) Sort the eigenvectors by their corresponding eigenvalues from largest to smallest (call new matrix P*)
    #May be unnecessary is eigenvalues/vectors are return in descending order
    idx = e_vals.argsort()[::-1]   
    e_vals = e_vals[idx]
    P_star = e_vects[:,idx]

#     display(e_vals)
#     display(P_star)
    
    #5) Calculate Z* = ZP* (new matrix Z* is a centered/standardized version of X's principle components)
    #Eigenvectors are the directions, Eigenvalues are the magnitudes/importance
    Z_star = Z @ P_star
    
    #6) Determine the top N features to keep
    topN = Z_star[:, :N]
#     display(topN)
    return topN

In [217]:
#Verify acccuracy with sklearn PCA

X_train = training[0:5, 0:5]
# display(X_train)
N = 2

In [218]:
from sklearn.decomposition import PCA as scikitPCA

#Center data
# mean = X_train.mean(axis=0)
# center_X = X_train - mean[np.newaxis, :]

# #Standardize data
# sd = np.std(center_X, axis=0)
# Z = center_X / sd
# # display(Z)

Z = X_train

pca = scikitPCA(n_components=N)
pca.fit(Z)

reduced_dim = pca.transform(Z)

display(reduced_dim)

display(X_train.shape)
display(reduced_dim.shape)

# display(pca.explained_variance_ratio_)
# display(pca.singular_values_)
# display(pca.get_covariance())
# display(pca.get_params())

# display(np.transpose(pca.components_))
# display(pca.components_)

array([[ 1.04725082e-04,  9.89889464e-05],
       [-4.15586840e-05, -3.41273120e-05],
       [ 2.96414581e-04, -6.18740550e-05],
       [-2.41627047e-04, -5.01569289e-05],
       [-1.17953931e-04,  4.71693496e-05]])

(5, 5)

(5, 2)

In [219]:
#My PCA Implementation

topNFeatures = PCA(X_train, N)
display(topNFeatures)

array([[-0.99164618,  0.10754743],
       [ 0.10605332,  0.59777868],
       [ 0.18620867, -2.3195306 ],
       [ 0.47105231,  1.30487501],
       [ 0.22833188,  0.30932949]])

In [212]:
# from sklearn.metrics import accuracy_score
# accuracy_score(reduced_dim, topNFeatures)

In [ ]:
def Kmeans(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """
    
    #1) Choose the number of clusters (K = N)
    
    #2) Initialize N centroids to "random" values of the data,
    #Either choose them at random: (Find the min and max of the data, then calculate random coordinates from there)
    #Or sort the dataset, split it into K portions and pick one datapoint from each portion as a centriod.
    
    #3) Reassign all points to the closest centroid
    #Calculate Euclidean distance between each point and each centroid, assign each point to the min dist centroid
    
    #4) Recalculate centroid coordinate based on point assignment
    #New centroid value is the average of all point that currently have that centroid's label
    
    #5) Repeat steps 3 and 4 until there is no change in centroid coordinates, or points stop switching clusters
    #Either keep track and only stop is all of the centroids don't change values
    #Or only repeat a fixed number of iterations

In [ ]:
def SklearnSupervisedLearning(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """
"

In [ ]:
def SklearnVotingClassifier(X_train,Y_train,X_test):
    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """


"""
Create your own custom functions for Matplotlib visualization of hyperparameter search. 
Make sure that plots are labeled and proper legends are used
""