In [2]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""
import numpy as np
import pandas as pd

df=pd.read_csv('data.csv')

In [3]:
data = df.to_numpy()
training_ind = np.random.rand(len(data)) <= 0.8
training = data[training_ind]
testing = data[~training_ind]
X_train = training[0:32734, 0:48]
Y_train = training[0:32734, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:8222, 0:48]
Y_test = testing[0:8222, 48:49]
Y_test = Y_test.flatten()

#k = 5
#print(KNN(X_train, X_test, Y_train, k))

In [4]:
def Accuracy(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    
    """

In [5]:
def Recall(y_true,y_pred):
     """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """

In [6]:
def Precision(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """

In [7]:
def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """

In [8]:
def ConfusionMatrix(y_true,y_pred):
    
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """  

In [15]:
X_train = training[0:800, 0:48]
Y_train = training[0:800, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:200, 0:48]
Y_test = testing[0:200, 48:49]
Y_test = Y_test.flatten()
k = 10

#Normalize the train and test data
X_min = np.min(X_train,axis = 0)
X_max = np.max(X_train,axis = 0)
X_minMat = np.tile(X_min, (X_train.shape[0],1))
X_maxMat = np.tile(X_max, (X_train.shape[0],1))
X_train_normal = np.true_divide(X_train-X_minMat, X_maxMat-X_minMat)

X_train = X_train_normal

X_min2 = np.min(X_test,axis = 0)
X_max2 = np.max(X_test,axis = 0)
X_minMat2 = np.tile(X_min2, (X_test.shape[0],1))
X_maxMat2 = np.tile(X_max2, (X_test.shape[0],1))
X_test_normal = np.true_divide(X_test-X_minMat2, X_maxMat2-X_minMat2)

X_test = X_test_normal

y_pred = np.array([])
for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)


In [16]:
from sklearn.metrics import accuracy_score
y_true = Y_test

display(y_true)
display(y_pred)

accuracy_score(y_true, y_pred)

array([ 9.,  9.,  5.,  2.,  4.,  6.,  1., 10., 10., 10.,  7.,  8.,  4.,
       11.,  7.,  8.,  6.,  6.,  5.,  4.,  7.,  2.,  5., 10.,  2.,  7.,
        5.,  9.,  6.,  9.,  2.,  6., 10.,  1.,  1.,  7.,  1.,  3.,  3.,
        2.,  5.,  6., 10.,  3.,  7.,  5.,  4.,  1.,  6.,  6.,  5.,  3.,
        1.,  4.,  9.,  1.,  8., 11.,  1., 11.,  1., 10.,  9.,  9.,  3.,
        9.,  5., 10.,  8.,  9., 11.,  7.,  6.,  5.,  6.,  6.,  6.,  5.,
       11., 11.,  7.,  2.,  7.,  8., 11.,  1.,  4.,  9.,  2.,  9.,  2.,
       11.,  6.,  1.,  5.,  6.,  1.,  3.,  5.,  8., 10.,  5.,  9.,  7.,
        1.,  9.,  6.,  7.,  4.,  1.,  9.,  5.,  5.,  5.,  2.,  3., 10.,
       11.,  4.,  8.,  7.,  4.,  1.,  1.,  2.,  7.,  6.,  8.,  3.,  2.,
        8.,  3.,  7.,  2.,  7.,  7., 11.,  8.,  4.,  6.,  1.,  6.,  9.,
        2.,  3.,  9.,  8.,  4.,  9., 11.,  5.,  8.,  4., 11.,  3.,  1.,
        9., 10., 11.,  2.,  7.,  6., 10., 11.,  6.,  2.,  4.,  1.,  2.,
       11.,  5.,  7., 10.,  4.,  5.,  7.,  4.,  5., 10.,  8.,  5

array([ 6.,  9.,  5.,  2.,  4.,  2.,  8., 10.,  3., 10.,  7.,  5.,  4.,
       11.,  7.,  5.,  3.,  1.,  4.,  4.,  7.,  2.,  4.,  1., 10.,  7.,
        3.,  6.,  3.,  9., 10.,  6., 10.,  6.,  6.,  7.,  3.,  3.,  3.,
        2.,  5.,  6.,  2.,  3.,  7.,  3.,  8.,  3.,  6.,  3.,  5.,  1.,
        6.,  5.,  9.,  1.,  8., 11.,  1., 11.,  1.,  6.,  9.,  1.,  8.,
        6.,  5., 10.,  6.,  3., 11.,  7.,  6.,  5.,  1.,  6.,  5.,  3.,
       11., 11.,  7., 10.,  7.,  8., 11.,  1.,  4.,  3.,  2.,  5.,  3.,
       11.,  1.,  6.,  8.,  1.,  6.,  3.,  5.,  6., 10.,  4.,  9.,  7.,
        1.,  6.,  6.,  7.,  4.,  6.,  6.,  8.,  1.,  5.,  2.,  3.,  2.,
       11.,  3.,  1.,  7.,  5.,  6.,  6.,  2.,  7.,  6.,  6.,  1.,  3.,
        8.,  1.,  7., 10.,  7.,  4., 11.,  5.,  4.,  6.,  6.,  6.,  9.,
        1.,  1.,  2.,  5.,  5.,  6., 11.,  5.,  6.,  4., 11.,  3.,  1.,
        9.,  1., 11.,  1.,  7.,  6., 10., 11.,  6.,  6.,  8.,  6.,  2.,
       11.,  5.,  7., 10.,  4.,  8.,  7.,  4.,  4., 10.,  8.,  8

0.56

In [29]:
mat = np.array([[[1,4],[7,5],[3,2]],[[3,5],[5,3],[1,2]],[[7,9],[5,3],[6,2]]])
display(mat)
m = mat.view(dtype=[('', mat.dtype)]*mat.shape[-1])
m.sort(axis=1)
mat
display(mat[:,0:2,:])

array([[[1, 4],
        [7, 5],
        [3, 2]],

       [[3, 5],
        [5, 3],
        [1, 2]],

       [[7, 9],
        [5, 3],
        [6, 2]]])

array([[[1, 4],
        [3, 2]],

       [[1, 2],
        [3, 5]],

       [[5, 3],
        [6, 2]]])

In [30]:
A = np.array([[1,2,3],[3,1,6]])
display(A)
B = np.array([[2,7,2],[8,2,4]])
display(B)
C = np.true_divide(A,B)
display(C)
mini = np.min(A,axis = 0)
maxi = np.max(A,axis = 0)
#display(mini)
min2 = np.tile(mini, (A.shape[0],1))
#display(min2)


array([[1, 2, 3],
       [3, 1, 6]])

array([[2, 7, 2],
       [8, 2, 4]])

array([[0.5       , 0.28571429, 1.5       ],
       [0.375     , 0.5       , 1.5       ]])

In [21]:
X_train = training[0:50, 0:48]
Y_train = training[0:50, 48:49]
Y_train = Y_train.flatten()
X_test = testing[0:10, 0:48]
Y_test = testing[0:10, 48:49]
Y_test = Y_test.flatten()

#display(X_train)
X_min = np.min(X_train,axis = 0)
#display(X_min)
X_max = np.max(X_train,axis = 0)
X_minMat = np.tile(X_min, (X_train.shape[0],1))
X_maxMat = np.tile(X_max, (X_train.shape[0],1))
X_train_normal = np.true_divide(X_train-X_minMat, X_maxMat-X_minMat)
#display(X_maxMat)

X_min2 = np.min(X_test,axis = 0)
#display(X_min)
X_max2 = np.max(X_test,axis = 0)
X_minMat2 = np.tile(X_min2, (X_test.shape[0],1))
X_maxMat2 = np.tile(X_max2, (X_test.shape[0],1))
X_test_normal = np.true_divide(X_test-X_minMat2, X_maxMat2-X_minMat2)


#display(final)
X_train_normal = np.transpose(X_train_normal)
dist = np.dot(X_test_normal, X_train_normal)


k = 6
trueLabel = np.tile(Y_train, (X_test_normal.shape[0],1))
Dist = np.array(np.dstack((dist, trueLabel)))
#Dist = np.array(Dist[0:3,0:3,0:2])
#display(Dist)
D = Dist.view(dtype=[('', Dist.dtype)]*Dist.shape[-1])
D.sort(axis=1)
# display(Dist)
topK = Dist[:,0:k,:]
# display(topK)
topK = topK[:,:,1].astype(int)
display(topK)
Y_pred = np.array([])
for vector in topK:
    counts = np.bincount(vector)
    majority = np.argmax(counts)
    Y_pred = np.append(Y_pred,majority)
display(Y_pred)
#=sortDist = np.sort(sortDist, axis = 2)
#display(sortDist)
#sortDist = sorted(data, key=lambda x: x[1])


array([[11, 10, 10,  8,  3,  6],
       [11,  5,  5,  6,  3, 10],
       [11,  5,  5,  3,  7,  6],
       [11, 11,  2, 10, 10,  6],
       [11,  5,  3,  5,  7,  6],
       [11, 11,  2, 10,  3,  6],
       [11, 11,  5,  5,  6,  3],
       [11,  7, 11,  3,  7,  5],
       [11, 11,  2, 10, 10,  6],
       [11, 11, 10, 10,  8,  2]])

array([10.,  5.,  5., 10.,  5., 11.,  5.,  7., 10., 10.])

In [25]:
from sklearn.metrics import accuracy_score

y_true = Y_test
display(y_true)

accuracy_score(y_true, Y_pred)

array([ 6.,  9., 10.,  4.,  1.,  7.,  3., 11.,  5.,  7.])

0.0

In [20]:
def KNN(X_train,X_test,Y_train, k):
    y_pred = np.array([])
    for point in X_test:
        dist = np.array([])
        for row in X_train:
            d = np.sqrt(np.sum((point-row)**2))
            dist = np.append(dist, d)
        attach = np.vstack((dist, Y_train))
        sortDist = attach[:,attach[0].argsort()]
        topK = sortDist[:,0:k]
        topK = topK[1].astype(int)
        counts = np.bincount(topK)
        majority = np.argmax(counts)
        y_pred = np.append(y_pred,majority)
    return y_pred
        
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    ##NP.tile np.repeat
    ##np.lin(norx)
    ##creating a matrix with same test row repeating operation on entire train matrix
    ##(A-B)^2 = A^2 - 2AB + B^2
    ##cosine distance also an option
    :rtype: numpy.ndarray
    """

In [17]:
X_train.shape

(800, 48)

In [18]:
X_test.shape

(200, 48)

In [ ]:
def RandomForest(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: numpy.ndarray
    """

In [ ]:
def PCA(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: numpy.ndarray
    """  

In [ ]:
def Kmeans(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """
    
    #1) Choose the number of clusters (K = N)
    
    #2) Initialize N centroids to "random" values of the data
    #Either choose them at random: (Find the min and max of the data, then calculate random coordinates from there)
    
    
    #Or sort the dataset, split it into K portions and pick one datapoint from each portion as a centriod.
    
    #3) Reassign all points to the closest centroid
    #Calculate Euclidean distance between each point and each centroid, assign each point to the min dist centroid
    
    #4) Recalculate centroid coordinate based on point assignment
    #New centroid value is the average of all point that currently have that centroid's label
    
    #5) Repeat steps 3 and 4 until there is no change in centroid coordinates, or points stop switching clusters
    #Either keep track and only stop is all of the centroids don't change values
    #Or only repeat a fixed number of iterations
    

In [ ]:
def SklearnSupervisedLearning(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """
"

In [ ]:
def SklearnVotingClassifier(X_train,Y_train,X_test):
    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """


"""
Create your own custom functions for Matplotlib visualization of hyperparameter search. 
Make sure that plots are labeled and proper legends are used
""